<?php

  /**
   * Implements hook_block_info().
   *
   * Declares a block to provide to Drupal. This can also specify block
   * configuration settings, like here where the cache is determined be the
   * user role.
   *
   * @url: https://api.drupal.org/api/drupal/modules!block!block.api.php/function/hook_block_info/7
   */
  function espn_news_block_info() {
    $blocks['espn_news'] = array(
      'info' => t('ESPN News'),
      'cache' => DRUPAL_CACHE_PER_ROLE,
    );

    return $blocks;
  }
  /**
   * Implements hook_help().
   *
   * You can add documentation and help here (in admin/help#espn_news). This
   * documentation can help the users use and extend you module.
   *
   * @url: https://api.drupal.org/api/drupal/modules!help!help.api.php/function/hook_help/7
   */
  function espn_news_help($path, $arg) {
    switch ($path) {
      case 'admin/setting/espn_news':
        return t('This module displays a block which shows a list recent ESPN sport news.');

      case 'admin/help#espn_news';
        $output = '<h2>' . t('About') . '</h2>';
        $output .= '<p>' . t('Displays recent sport news from ESPN.') . '</p>';
        $output .= '<p>' . t('The news is fetched with ESPNs open REST API, all rights reserved to ESPN (2014).') . '</p>';
        return $output;
    }
  }

   /**
   * Implements hook_block_view().
   *
   * Creates content for our block. It sets the title for the block, and the
   * content.
   *
   * @url: https://api.drupal.org/api/drupal/modules!block!block.api.php/function/hook_block_view/7
   */
  function espn_news_block_view($delta = '') {
    $block = array();

    switch ($delta) {
      case 'espn_news':

      // Set block title.
      $block['subject'] = t('ESPN News');

      // Set block content.
      $block['content'] = 'Hello World';
    }

    return $block;
  }

  /**
   * Implements hook_menu().
   *
   * Defines paths to provide page callbacks and menu items for the site.
   * Here it defines a configuration page with callback to a form, we'll
   * create later on.
   *
   * @url: https://api.drupal.org/api/drupal/modules!system!system.api.php/function/hook_menu/7
   */
  function espn_news_menu() {
    $items = array();

    // Module configuration page.
    $items['admin/config/content/espn_news'] = array(
      'title' => 'ESPN News',
      'description' => 'Configuration for ESPN News module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('espn_news_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );

    return $items;
  }

    function espn_news_form($form, &$form_state) {
    // Fieldset.
    $form['espn_api'] = array(
      '#type' => 'fieldset',
      '#title' => t('ESPN API'),
      '#weight' => 0,
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );
    // Textfield for API key.
    $form['espn_api']['espn_news_api_key'] = array(
      '#type' => 'textfield',
      '#title' => t('ESPN API key'),
      '#default_value' => variable_get('espn_news_api_key'),
      '#size' => 40,
      '#maxlength' => 24,
      '#description' => t('API from ESPN Developer Center (http://developer.espn.com/apps/mykeys).'),
      '#required' => TRUE,
    );

    return system_settings_form($form);
  }